name: Build, test, and publish development wheels on PyPI

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  pkg_name: deltakit-compile

jobs:
  build-test-wheels:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Needed to get the last commit involving each package to tag dev versions.
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build deltakit-compile wheel
        run: uv build --no-sources -o ./dist
      - name: Upload wheels artefacts
        uses: actions/upload-artifact@v7
        with:
          name: deltakit-compile
          path: ./dist/
          retention-days: 1

  test-wheel:
    name: Test imports on ${{ matrix.os }}
    needs: [build-test-wheels]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14', '3.15']
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Make dist dir
        run: mkdir dist
      - name: Recover deltakit distribution files
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ env.pkg_name }}
          path: ./dist/
          merge-multiple: true
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
      - name: Test installs in Unix systems
        if: matrix.os != 'windows-latest'
        run: |
          uv venv --python ${{ matrix.python-version }}
          uv pip install --pre dist/*.whl
          uv run python -c "import deltakit_compile"
      - name: Test installs on Windows OS
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          uv venv --python ${{ matrix.python-version }}
          uv pip install --pre (Get-ChildItem dist/*.whl).FullName
          uv run python -c "import deltakit_compile"

  test-sdist:
    name: Test imports after sdists installs
    needs: [build-test-wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Make dist dir
        run: mkdir dist
      - name: Recover deltakit distribution files
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ env.pkg_name }}
          path: ./dist/
          merge-multiple: true
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
      - name: Test install and imports
        run: |
          uv venv --python 3.10
          uv pip install --pre dist/*.tar.gz
          uv run python -c "import deltakit_compile"

  set-pre-version:
    name: Sets project prerelease versions
    runs-on: ubuntu-latest
    needs: [test-wheel, test-sdist]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install release dependencies
        run: uv sync --python 3.14 --group release
      - name: Set prerelease version with short commit hash.
        run: |
          git config --global --add safe.directory /__w/deltakit_compile/deltakit_compile
          COMMIT_HASH=$(git rev-parse --short HEAD)
          SECS_SINCE_EPOCH=$(date +%s)
          uv run --no-sync python3 -m tools.set_pre_version -t "$SECS_SINCE_EPOCH"
      - name: Commit current state of project
        run: |
          git config user.name "riv-dev-bot"
          git config user.email "devbot@riverlane.com"
          git add -A
          git commit -m "chore: set prerelease version"
      - name: Upload updated project
        uses: actions/upload-artifact@v7
        with:
          name: prerelease-proj
          path: .

  build-wheels-for-publishing:
    name: Build distributions
    needs: [set-pre-version]
    runs-on: ubuntu-latest
    steps:
      - name: Recover prerelease proj
        uses: actions/download-artifact@v8
        with:
          name: prerelease-proj
          path: .
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
      - name: Build deltakit subpackages wheel
        run: uv build --no-sources -o ./dist
      - name: Upload wheels artefacts
        uses: actions/upload-artifact@v7
        with:
          name: publish-${{ env.pkg_name }}
          path: ./dist
          retention-days: 1

  publish:
    name: Publish Python distribution to PyPI
    needs: [build-wheels-for-publishing]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.pkg_name }}
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Make dist dir
        run: mkdir ./dist
      - name: Recover deltakit-compile distribution files
        uses: actions/download-artifact@v8
        with:
          pattern: publish-${{ env.pkg_name }}
          path: ./dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
